baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Free Genomics"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|CONTEXT|GO\w+)$']

  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^CONTEXT$']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

[markup]
  defaultMarkdownHandler      = "goldmark"
  [markup.blackfriday]
    smartypants             = true
    smartypantsQuotesNBSP   = false
    angledQuotes            = false
    fractions               = true
    smartDashes             = true
    latexDashes             = true
    hrefTargetBlank         = true
    plainIDAnchors          = true
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
